MCOPY opcode (EIP-5656)
huff-language/huff-rs pull request #289
Opened 2023-07-18 13:00 UTC by gzanitti

## Overview

This PR introduces the possibility to compile a new instruction (MCOPY) introduced in `EIP-5656`.

The changes needed seem to be minimal (just added a new variant to the `Opcode` enum in `evm.rs`, so that the parser/bytecodegen will be able to understand the new opcode), but it was a good way to get acquainted with the code base.

I'd like to add a small test, something as simple as compiling:
``` 
#define macro MAIN() = {
    0x00
    0x00
    0x20
    mcopy
}
```
which becomes `5f5f6020205e`, but I couldn't find the right place to put it (and maybe it's not necessary for such a trivial change).

I look forward to your recommendations & corrections, so please, feel free to leave any comments you may have :smiley:

2023-08-28 21:53 UTC, Maddiaa0 requested changes
Apologies for the delay in the review. 

Overall looks awesome, could you add a small test covering its usage. Once thats in lets get it merged!

2023-08-29 19:13 UTC, gzanitti commented
> Apologies for the delay in the review.
> 
> Overall looks awesome, could you add a small test covering its usage. Once thats in lets get it merged!

Don't worry, there's no rush. As for the test, my idea was to add a test similar to the one I mentioned at the beginning of this thread (something that checks the transformation of the opcode into its corresponding bytecode), but that is something that already happens [here](https://github.com/huff-language/huff-rs/blob/f809070738e9675fd9760880698ec60dbc13c7ba/huff_lexer/tests/opcodes.rs#L9). Do you consider that any other type of test is necessary?

2023-09-02 13:57 UTC, Maddiaa0 commented
> > Apologies for the delay in the review.
> > Overall looks awesome, could you add a small test covering its usage. Once thats in lets get it merged!
> 
> Don't worry, there's no rush. As for the test, my idea was to add a test similar to the one I mentioned at the beginning of this thread (something that checks the transformation of the opcode into its corresponding bytecode), but that is something that already happens [here](https://github.com/huff-language/huff-rs/blob/f809070738e9675fd9760880698ec60dbc13c7ba/huff_lexer/tests/opcodes.rs#L9). Do you consider that any other type of test is necessary?

Ah thats absolutely good enough!

2023-09-02 13:57 UTC, Maddiaa0 approved these changes

2023-09-02 13:57 UTC, merged